export default AppImages = {
    openEye: require('../assets/Images/openEye.png'),
    closeEye: require('../assets/Images/closeEye.png'),
    loginImage: require('../assets/Images/login.jpg'),
    singUp: require('../assets/Images/signUp.jpg'),
    backButton: require('../assets/Images/backButton.png'),
    waitImage: require('../assets/Images/wait.jpg'),
    shopDetail: require('../assets/Images/shopDetailScreen.jpg'),
    dropdownIcon: require('../assets/Images/dropdownIcon.png'),
    otp: require('../assets/Images/otp.jpg'),
    dashboardIcon: require('../assets/Images/dashboardIcon.png'),
    searchIcon: require('../assets/Images/search.png'),
    profileIcon: require('../assets/Images/profile.png'),
    notificationIcon: require('../assets/Images/notification.png'),
}